import { ICourse } from '../../@features/courses/models/course.model';

export const COURSES: ICourse[] = [
  {
    courseCode: 'CSC 101',
    courseTitle: 'Introduction to Computer Science',
    department: 'Computer Science',
    faculty: 'Faculty of Science',
    semester: '1st Semester',
    school: 'School of Science',
    level: '400LVL',
    courseLoad: 3,
    lecturer: 'John Doe',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    courseCode: 'CSC 101',
    courseTitle: 'Introduction to Computer Science',
    department: 'Computer Science',
    faculty: 'Faculty of Science',
    semester: '1st Semester',
    school: 'School of Science',
    level: '400LVL',
    courseLoad: 3,
    lecturer: 'John Doe',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    courseCode: 'CSC 101',
    courseTitle: 'Introduction to Computer Science',
    department: 'Computer Science',
    faculty: 'Faculty of Science',
    semester: '1st Semester',
    school: 'School of Science',
    level: '400LVL',
    courseLoad: 3,
    lecturer: 'John Doe',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    courseCode: 'CSC 101',
    courseTitle: 'Introduction to Computer Science',
    department: 'Computer Science',
    faculty: 'Faculty of Science',
    semester: '1st Semester',
    school: 'School of Science',
    level: '400LVL',
    courseLoad: 3,
    lecturer: 'John Doe',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
