import { IMenu } from '../models/menu.model';

export const COURSE_ADVISOR_MENU: IMenu[] = [
  {
    label: 'Dashboard',
    active_icon: 'icons/menu/dashboard-active.svg',
    inactive_icon: 'icons/menu/dashboard-active.svg',
    route: 'dashboard',
    has_sub_menu: false,
    isActive: true,
  },
  {
    label: 'Courses',
    active_icon: 'icons/menu/courses-inactive.svg',
    inactive_icon: 'icons/menu/courses-inactive.svg',
    route: 'courses',
    has_sub_menu: false,
    isActive: true,
  },
  {
    label: 'My Result',
    active_icon: 'icons/menu/my-result-inactive.svg',
    inactive_icon: 'icons/menu/my-result-inactive.svg',
    route: 'my-result',
    has_sub_menu: false,
    isActive: true,
  },
  {
    label: 'Result Management',
    active_icon: 'icons/menu/result-management-inactive.svg',
    inactive_icon: 'icons/menu/result-management-inactive.svg',
    route: 'result-management',
    has_sub_menu: false,
    isActive: true,
  },
  {
    label: 'Schedule',
    active_icon: '',
    inactive_icon: '',
    route: 'schedule',
    has_sub_menu: false,
    isActive: false,
  },
  {
    label: 'Notifications',
    active_icon: 'icons/menu/notification-inactive.svg',
    inactive_icon: 'icons/menu/notification-inactive.svg',
    route: 'notifications',
    has_sub_menu: false,
    isActive: true,
  },
  {
    label: 'Support & Help',
    active_icon: 'icons/menu/support-inactive.svg',
    inactive_icon: 'icons/menu/support-inactive.svg',
    route: 'support',
    has_sub_menu: false,
    isActive: true,
  },
  {
    label: 'User Settings',
    active_icon: 'icons/menu/settings-inactive.svg',
    inactive_icon: 'icons/menu/settings-inactive.svg',
    route: 'user-settings',
    has_sub_menu: false,
    isActive: true,
  },
];

export const COURSE_CORDINATOR_MENU: IMenu[] = [
  {
    label: 'Dashboard',
    active_icon: 'icons/menu/dashboard-active.svg',
    inactive_icon: 'icons/menu/dashboard-active.svg',
    route: 'dashboard',
    has_sub_menu: false,
    isActive: true,
  },
  {
    label: 'Result Management',
    active_icon: 'icons/menu/result-management-inactive.svg',
    inactive_icon: 'icons/menu/result-management-inactive.svg',
    route: 'result-management',
    has_sub_menu: false,
    isActive: true,
  },
  {
    label: 'Statistics',
    active_icon: '',
    inactive_icon: '',
    route: 'statistics',
    has_sub_menu: false,
    isActive: false,
  },
  {
    label: 'History',
    active_icon: 'icons/menu/notification-inactive.svg',
    inactive_icon: 'icons/menu/notification-inactive.svg',
    route: 'history',
    has_sub_menu: false,
    isActive: true,
  },
  {
    label: 'FAQ',
    active_icon: 'icons/menu/notification-inactive.svg',
    inactive_icon: 'icons/menu/notification-inactive.svg',
    route: 'faq',
    has_sub_menu: false,
    isActive: true,
  },
  {
    label: 'Support & Help',
    active_icon: 'icons/menu/support-inactive.svg',
    inactive_icon: 'icons/menu/support-inactive.svg',
    route: 'support',
    has_sub_menu: false,
    isActive: true,
  },
  {
    label: 'User Settings',
    active_icon: 'icons/menu/settings-inactive.svg',
    inactive_icon: 'icons/menu/settings-inactive.svg',
    route: 'user-settings',
    has_sub_menu: false,
    isActive: true,
  },
];
